// app/components/guild/settings/moderation-settings.vue
<template>
  <layout-settings-section title="Punishment Settings">
    <p>These settings affect what WolfStar does when you're punishing (ban, kick, mute, etc) someone.</p>
    <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
      <SelectBoolean
        v-for="{ description, key, name } in moderationConfig.keys"
        :key="key"
        :title="name"
        :model-value="guildSettings[key]"
        :description="description"
        @update:model-value="updateModerationSetting(key, $event)"
      />
    </div>
  </layout-settings-section>
</template>

<script setup lang="ts">
const { moderationConfig, guildSettings, updateModerationSetting } = useGuildModeration()
</script>

// src/components/pages/Settings/ModerationSettings.tsx
import { ConfigurableModerationKeys } from '@config/SettingsDataEntries';
import { useGuildSettingsChangesContext } from '@contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '@contexts/Settings/GuildSettingsContext';
import Section from '@layout/Settings/Section';
import SimpleGrid from '@material/SimpleGrid';
import SelectBoolean from '@selects/SelectBoolean';
import { memo, type FC } from 'react';

const ModerationSettings: FC = () => {
	const { guildSettings } = useGuildSettingsContext();
	const { setGuildSettingsChanges } = useGuildSettingsChangesContext();

	return (
		<Section title="Punishment Settings">
			<p>These settings affect what WolfStar does when you're punishing (ban, kick, mute, etc) someone.</p>
			<SimpleGrid>
				{ConfigurableModerationKeys.map(({ description, key, name }, index) => (
					<SelectBoolean
						key={index}
						title={name}
						currentValue={guildSettings[key]}
						description={description}
						onChange={(event) =>
							setGuildSettingsChanges({
								[key]: event.target.checked
							})
						}
					/>
				))}
			</SimpleGrid>
		</Section>
	);
};

export default memo(ModerationSettings);
