// src/components/pages/Settings/ChannelSettings.tsx
import { ConfigurableIgnoreChannels, ConfigurableLoggingChannels } from '@config/SettingsDataEntries';
import { useGuildDataContext } from '@contexts/Settings/GuildDataContext';
import { useGuildSettingsChangesContext } from '@contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '@contexts/Settings/GuildSettingsContext';
import PageHeader from '@layout/Settings/PageHeader';
import Section from '@layout/Settings/Section';
import SimpleGrid from '@material/SimpleGrid';
import SelectChannel from '@selects/SelectChannel';
import SelectChannels from '@selects/SelectChannels';
import { handleResetKey } from '@utils/util';
import { memo, type FC } from 'react';

const ChannelSettings: FC = () => {
	const { guildData } = useGuildDataContext();
	const { guildSettings } = useGuildSettingsContext();
	const { guildSettingsChanges, setGuildSettingsChanges } = useGuildSettingsChangesContext();

	return (
		<>
			<PageHeader
				title="Channels"
				subtitle={
					<>
						Here you can configure different kinds of channels for WolfStar. Hover over a button to get more information for that specific
						channel.
					</>
				}
			/>

			<Section title="Logging Channels">
				<SimpleGrid
					direction="row"
					justifyContent="flex-start"
					gridItemProps={{
						xs: 12,
						sm: 12,
						md: 4,
						lg: 4,
						xl: 4
					}}
				>
					{ConfigurableLoggingChannels.map(({ name, description, key }, index) => (
						<SelectChannel
							key={index}
							tooltipTitle={description}
							value={guildSettings[key]}
							onReset={() => handleResetKey(guildSettingsChanges, setGuildSettingsChanges, key)}
							onChange={(channel: (typeof guildSettings)[typeof key]) => {
								return setGuildSettingsChanges({ [key]: channel });
							}}
							guild={guildData}
							label={name}
							ButtonProps={{
								fullWidth: true,
								sx: {
									minHeight: {
										lg: 'inherit',
										md: 60,
										xs: 'inherit'
									},
									textAlign: 'left'
								}
							}}
						/>
					))}
				</SimpleGrid>
			</Section>
			<Section
				title="Logging Ignore Channels"
				sx={{
					mt: {
						lg: (theme) => theme.spacing(10),
						xs: (theme) => theme.spacing(5)
					}
				}}
			>
				<SimpleGrid
					direction="row"
					justifyContent="flex-start"
					gridItemProps={{
						xs: 12,
						sm: 12,
						md: 4,
						lg: 4,
						xl: 4
					}}
				>
					{ConfigurableIgnoreChannels.map(({ name, description, key }, index) => (
						<SelectChannels
							key={index}
							tooltipTitle={description}
							value={guildSettings[key]}
							onReset={() => handleResetKey(guildSettingsChanges, setGuildSettingsChanges, key)}
							onChange={(channel: (typeof guildSettings)[typeof key]) => setGuildSettingsChanges({ [key]: channel })}
							guild={guildData}
							label={name}
							ButtonProps={{
								fullWidth: true,
								sx: {
									minHeight: {
										lg: 'inherit',
										md: 60,
										xs: 'inherit'
									},
									textAlign: 'left'
								}
							}}
						/>
					))}
				</SimpleGrid>
			</Section>
		</>
	);
};

export default memo(ChannelSettings);

// app/components/guild/settings/channel-settings.vue
<template>
  <div role="region" aria-label="Channel Settings">
    <!-- Header Section -->
    <section>
      <h2 class="text-2xl font-bold">Channels</h2>
      <p class="mt-2 text-base-content/80">
        Here you can configure different kinds of channels for WolfStar. Hover over a button to get more information for that specific
        channel.
      </p>
    </section>

    <!-- Logging Channels Section -->
    <SettingsSection title="Logging Channels">
      <div v-if="guildData" class="grid grid-cols-1 gap-4 md:grid-cols-3">
        <div v-for="channel in ConfigurableLoggingChannels" :key="channel.key">
          <SelectChannel
            v-model="settings[channel.key]"
            :label="channel.name"
            :tooltip="channel.description"
            :guild="guildData"
            class="w-full"
            @reset="resetChanges(channel.key)"
          />
        </div>
      </div>
    </SettingsSection>

    <!-- Ignore Channels Section -->
    <SettingsSection title="Logging Ignore Channels" class="mt-8">
      <div v-if="guildData" class="grid grid-cols-1 gap-4 md:grid-cols-3">
        <div v-for="channel in ConfigurableIgnoreChannels" :key="channel.key">
          <SelectChannels
            v-model="settings[channel.key]"
            :label="channel.name"
            :tooltip="channel.description"
            :guild="guildData"
            class="w-full"
            @reset="resetChanges(channel.key)"
          />
        </div>
      </div>
    </SettingsSection>
  </div>
</template>

<script setup lang="ts">
// Get the settings data from your store
const guildData = useGuildData()
const { settings, resetChanges } = useGuildSettings()
</script>

<style scoped>
.md-grid-cols-3 {
  @apply grid-cols-3;
}
</style>
