// src/components/presentational/CommandsPage/Command.tsx
import type { FlattenedCommand } from '@config/types/ApiData';
import BrushIcon from '@mui/icons-material/BrushTwoTone';
import CodeIcon from '@mui/icons-material/CodeTwoTone';
import CreateIcon from '@mui/icons-material/CreateTwoTone';
import ExamplesIcon from '@mui/icons-material/EmojiObjects';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import Chips from '@presentational/CommandsPage/Chips';
import { reactStringReplace } from '@utils/reactStringReplace';
import ReminderIcon from 'mdi-react/BellAlertIcon';
import HelpRhombusIcon from 'mdi-react/HelpRhombusIcon';
import { memo, type FC } from 'react';
import ExtendedHelpBody from './ExtendedHelpBody';
import ExtendedHelpSectionHeader from './ExtendedHelpSectionHeader';

import { Accordion, AccordionActions, AccordionDetails, AccordionSummary, Grid, Typography } from '@mui/material';

interface CommandProps {
	command: FlattenedCommand;
}

const resolveMultilineString = (str: string | string[], multiline = false): string => {
	return Array.isArray(str)
		? resolveMultilineString(str.join(multiline ? '\n' : ' '), multiline)
		: str
				.split('\n')
				.map((line) => line.trim())
				.join(multiline ? '\n\n' : ' ');
};

const Command: FC<CommandProps> = ({ command }) => {
	return (
		<Grid
			item
			sx={{
				flex: '1 1 30%',
				minWidth: '100%',
				my: 2,
				transition: 'width 0.2s ease-in-out',
				maxWidth: {
					sm: 'inherit',
					xs: 'none'
				},
				mx: {
					sm: 'inherit',
					xs: 0
				}
			}}
		>
			<Accordion TransitionProps={{ unmountOnExit: true }} elevation={4} sx={{ bgcolor: 'secondary.light' }}>
				<AccordionSummary expandIcon={<ExpandMoreIcon />}>
					<Grid container direction="row" alignItems="center" justifyContent="flex-start" alignContent="flex-start">
						<Grid item xs={12} md={3}>
							<Typography
								sx={{
									fontSize: (theme) => theme.typography.pxToRem(20),
									fontWeight: 'bolder'
								}}
							>
								{reactStringReplace(`s!${command.name}`, /(.{10})/g, (match, index) => (
									<span key={index}>
										<wbr />
										{match}
									</span>
								))}
							</Typography>
						</Grid>
						<Grid item xs={12} md={9}>
							<Typography
								component="span"
								sx={{
									fontSize: (theme) => theme.typography.pxToRem(15),
									color: 'text.secondary'
								}}
							>
								<ExtendedHelpBody body={command.description} />
							</Typography>
						</Grid>
					</Grid>
				</AccordionSummary>
				<AccordionDetails>
					<Grid container direction="column">
						{command.extendedHelp.usages && (
							<>
								<Grid item>
									<ExtendedHelpSectionHeader icon={<CreateIcon />} header="Command Usage" />
								</Grid>
								<Grid item>
									{command.extendedHelp.usages.map((usage, key) => (
										<ExtendedHelpBody key={key} body={`\`WolfStar, ${command.name} ${usage}\``} />
									))}
								</Grid>
							</>
						)}

						{command.extendedHelp.extendedHelp && (
							<>
								<Grid
									item
									sx={{
										...(Boolean(command.extendedHelp.usages) && { mt: 4 })
									}}
								>
									<ExtendedHelpSectionHeader icon={<HelpRhombusIcon />} header="Extended Help" />
								</Grid>
								<Grid item>
									<ExtendedHelpBody body={resolveMultilineString(command.extendedHelp.extendedHelp, true)} />
								</Grid>
							</>
						)}

						{command.extendedHelp.explainedUsage && (
							<>
								<Grid item sx={{ mt: 4 }}>
									<ExtendedHelpSectionHeader icon={<CodeIcon />} header="Explained Usage" />
								</Grid>
								<Grid item>
									<ExtendedHelpBody
										body={command.extendedHelp.explainedUsage
											.map(([arg, desc]) => `- **${arg}**: ${resolveMultilineString(desc)}`)
											.join('\n')}
									/>
								</Grid>
							</>
						)}

						{command.extendedHelp.possibleFormats && (
							<>
								<Grid item sx={{ mt: 4 }}>
									<ExtendedHelpSectionHeader icon={<BrushIcon />} header="Possible Formats" />
								</Grid>
								<Grid item>
									<ExtendedHelpBody
										body={command.extendedHelp.possibleFormats.map(([type, example]) => `- **${type}**: ${example}`).join('\n')}
									/>
								</Grid>
							</>
						)}

						{command.extendedHelp.examples && (
							<>
								<Grid item sx={{ mt: 4 }}>
									<ExtendedHelpSectionHeader icon={<ExamplesIcon />} header="Examples" />
								</Grid>
								<Grid item>
									<ExtendedHelpBody
										body={command.extendedHelp.examples
											.map((example) => `- WolfStar, ${command.name}${example ? ` *${example}*` : ''}`)
											.join('\n')}
									/>
								</Grid>
							</>
						)}

						{command.extendedHelp.reminder && (
							<>
								<Grid item sx={{ mt: 4 }}>
									<ExtendedHelpSectionHeader icon={<ReminderIcon />} header="Reminder" />
								</Grid>
								<Grid item>
									<ExtendedHelpBody body={command.extendedHelp.reminder} />
								</Grid>
							</>
						)}
					</Grid>
				</AccordionDetails>
				<AccordionActions>
					<Chips command={command} />
				</AccordionActions>
			</Accordion>
		</Grid>
	);
};

export default memo(Command);

// app/components/commands/command.vue
<template>
  <div class="my-2 max-w-none min-w-full flex-1 transition-all duration-200">
    <div class="bg-secondary-light card">
      <div class="card-body">
        <div class="card-title">
          <div v-if="!loading" class="flex flex-row items-center gap-4">
            <div class="w-full md:w-1/3">
              <span class="text-lg font-bold">s!{{ command.name }}</span>
            </div>
            <div class="w-full md:w-2/3">
              <span class="text-sm text-secondary">{{ command.description }}</span>
            </div>
          </div>
          <div v-else class="flex flex-row gap-4">
            <div class="h-8 w-32 skeleton"></div>
            <div class="h-6 w-64 skeleton"></div>
          </div>
        </div>

        <div v-if="loading" class="collapse-content">
          <div class="flex flex-col">
            <template v-if="command.extendedHelp.usages">
              <CommandsExtendedHelpSectionHeader icon="mdi-pencil" header="Command Usage" />
              <div v-for="(usage, index) in command.extendedHelp.usages" :key="index">
                <CommandsExtendedHelpBody :body="`\`WolfStar, ${command.name} ${usage}\``" />
              </div>
            </template>
            <template v-else-if="loading">
              <div class="flex flex-col gap-4 p-4">
                <div v-for="i in 3" :key="i" class="h-24 w-full skeleton"></div>
              </div>
            </template>

            <template v-if="cextendedHelp">
              <CommandsExtendedHelpSectionHeader icon="mdi-help-rhombus" header="Extended Help" />
              <CommandsExtendedHelpBody :body="resolvedExtendedHelp!" />
            </template>

            <template v-if="explainedUsage">
              <CommandsExtendedHelpSectionHeader icon="mdi-code-tags" header="Explained Usage" />
              <CommandsExtendedHelpBody :body="explainedUsage!" />
            </template>

            <template v-if="possibleFormats">
              <CommandsExtendedHelpSectionHeader icon="mdi-brush" header="Possible Formats" />
              <CommandsExtendedHelpBody :body="possibleFormats!" />
            </template>

            <template v-if="examples">
              <CommandsExtendedHelpSectionHeader icon="mdi-lightbulb-outline" header="Examples" />
              <CommandsExtendedHelpBody :body="examples" />
            </template>

            <template v-if="creminder">
              <CommandsExtendedHelpSectionHeader icon="mdi-bell-alert" header="Reminder" />
              <CommandsExtendedHelpBody :body="reminder" />
            </template>
          </div>
        </div>
        <div class="card-actions justify-end border-t border-gray-200 pt-4 dark:border-gray-800">
          <CommandsChips :command="command" :loading="loading" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
interface CommandProps {
  command: FlattenedCommand
  loading?: boolean
}

const props = withDefaults(defineProps<CommandProps>(), {
  loading: false,
})

function resolveContent(content: string | string[], multiline = false) {
  if (!content)
    return null
  try {
    return Array.isArray(content) ? content.join(multiline ? '\n\n' : ' ') : content.trim()
  }
  catch {
    return null
  }
}

const resolvedExtendedHelp = computed(() => resolveContent(props.command.extendedHelp.extendedHelp, true))

const explainedUsage = computed(() =>
  resolveContent(
    props.command.extendedHelp.explainedUsage.map(([arg, desc]) => `- **${arg}**: ${resolveContent(desc)}`),
    true,
  ),
)

const possibleFormats = computed(() =>
  resolveContent(
    props.command.extendedHelp.possibleFormats.map(([type, example]) => `- **${type}**: ${example}`),
    true,
  ),
)

const examples = computed(() =>
  resolveContent(
    props.command.extendedHelp.examples.filter(example => example !== null).map(example => `- WolfStar, ${props.command.name}*${example}*`),
    true,
  ),
)

const reminder = computed(() => resolveContent(props.command.extendedHelp.reminder, true))
</script>

<style scoped>
.chips-container {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.chip {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-radius: 0.5rem;
  background-color: var(--primary-color);
  padding: 0.5rem 1rem;
  color: white;
}

.chip.secondary {
  background-color: var(--secondary-color);
}
</style>
